In [1]:
# This is a unit test case for Maze.py
import numpy as np
import pandas as pd

dataFrame = pd.read_csv('testworlds/world01.csv', header=None)
maze_matrix = dataFrame.values

print(maze_matrix)

[[3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0 0]
 [0 5 1 0 0 0 1 0 0 0]
 [0 5 1 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]]


In [2]:
from Maze import Maze

maze = Maze(maze_matrix)

print(maze.get_start_pos())

print(maze.get_goal_pos())

move_up = 0
move_down = 1
move_left = 2
move_right = 3

(9, 4)
(0, 0)


In [3]:
maze.print_map()

--------------------
G         
          
          
  XXXXX   
 ~X   X   
 ~X   X   
  X   X   
          
          
    S     
--------------------


In [5]:
Qtable = np.zeros((100, 4))

Qtable[1][0] = 2
Qtable[1][1] = 3
Qtable[1][2] = 9
Qtable[1][3] = 1

Qvalue = Qtable[1]

indices = Qvalue.argmax()

print(np.argmax(Qtable[1,:])

print(indices)

print(Qtable[1, 0])
print(Qtable[1][0])

2
2
2.0
2.0
