In [4]:
# This is a unit test case for Maze.py
import numpy as np
import pandas as pd

dataFrame = pd.read_csv('testworlds/world01.csv', header=None)
maze_matrix = dataFrame.values

print(maze_matrix)

[[3 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 0 0]
 [0 5 1 0 0 0 1 0 0 0]
 [0 5 1 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0]]


In [5]:
from Maze import Maze

maze = Maze(maze_matrix)

print(maze.get_start_pos())

print(maze.get_goal_pos())

move_up = 0
move_down = 1
move_left = 2
move_right = 3

IndentationError: expected an indented block (Maze.py, line 97)

In [4]:
# Test move function
start_point = maze.get_start_pos()

# move up newpos should be (8, 4) and reward should be -1
newpos, reward = maze.move(start_point, move_up)
print(start_point, "move up to newpos=", newpos, " reward=", reward)

# move down newpos should be (9, 4) and reward should be -1
newpos, reward = maze.move(start_point, move_down)
print(start_point, "move down to newpos=", newpos, " reward=", reward)

# move down newpos should be (9, 3) and reward should be -1
newpos, reward = maze.move(start_point, move_left)
print(start_point, "move left to newpos=", newpos, " reward=", reward)

# move down newpos should be (9, 5) and reward should be -1
newpos, reward = maze.move(start_point, move_right)
print(start_point, "move right to newpos=", newpos, " reward=", reward)

# move left at (5, 0) should be (5, 0) and reward should be -1
newpos, reward = maze.move((5, 0), move_left)
print((5, 0), "move left to newpos=", newpos, " reward=", reward)

# move right at (5, 0) should be (5, 1) and reward should be -100
newpos, reward = maze.move((5, 0), move_right)
print((5, 0), "move right to newpos=", newpos, " reward=", reward)

# move right at (3, 1) should be (3, 1) and reward should be -1
newpos, reward = maze.move((3, 1), move_right)
print((3, 1), "move right to newpos=", newpos, " reward=", reward)

# move right at (0, 9) should be (0, 9) and reward should be -1
newpos, reward = maze.move((0, 9), move_right)
print((0, 9), "move right to newpos=", newpos, " reward=", reward)

# move right at (0, 9) should be (0, 9) and reward should be -1
newpos, reward = maze.move((0, 9), move_up)
print((0, 9), "move up to newpos=", newpos, " reward=", reward)

# move up at (1, 0) should be (0, 0) and reward should be 1
newpos, reward = maze.move((1, 0), move_up)
print((1, 0), "move up to newpos=", newpos, " reward=", reward)

(9, 4) move up to newpos= (8, 4)  reward= -1
(9, 4) move down to newpos= (9, 4)  reward= -1
(9, 4) move left to newpos= (9, 3)  reward= -1
(9, 4) move right to newpos= (9, 5)  reward= -1
(5, 0) move left to newpos= (5, 0)  reward= -1
(5, 0) move right to newpos= (5, 1)  reward= -100
(3, 1) move right to newpos= (3, 1)  reward= -1
(0, 9) move right to newpos= (0, 9)  reward= -1
(0, 9) move up to newpos= (0, 9)  reward= -1
(1, 0) move up to newpos= (0, 0)  reward= 1


In [5]:
maze.print_map()

--------------------
G         
          
          
  XXXXX   
 ~X   X   
 ~X   X   
  X   X   
          
          
    S     
--------------------


In [12]:
import random

oArray = [0,1,2,3]

print (oArray)

oArray.remove(2)

print (oArray)

p = random.random()

0.27170701527821484
[0, 1, 2, 3]
[0, 1, 3]
